### ISSUE TITLE
Help installing your tool

### ISSUE THREAD

**Issue by Drixled** [toothbrush/debounce-mac#3]
Hi Toohbrush, sorry for bother you using a PR but I cannot find another method to contact with you. I'm seeking for help because I recently bought a new mechanical keyboard (NightFox by Kono) and I realize that 2 keys "n" and "c" suffer bouncing or key chattering. I installed your tool but I don`t now if I need any extra configuration or something else because I'm having the same issues.

Thanks for your help.

**Comment by boboG** [comment]
Hi Drixled,

I‘m just a user. Or to be more precise, I have been because I got my machanical keyboard fixed. That is what I recommend to you. Why life with a defective keyboard?

If you start debounce via a shell with „sudo ./debounce“ it should tell you if it is working. Newer macOS releases need extended permissions for tool like debounce to work properly.

**Comment by Drixled** [comment]
> Hi Drixled,
> 
> I‘m just a user. Or to be more precise, I have been because I got my machanical keyboard fixed. That is what I recommend to you. Why life with a defective keyboard?
> 
> If you start debounce via a shell with „sudo ./debounce“ it should tell you if it is working. Newer macOS releases need extended permissions for tool like debounce to work properly.

Thank you very much boboG, it works.

**Comment by toothbrush** [comment]
Sorry, i only just saw these messages now!  They got lost in the many Github notifications! 😊  I'm glad this tool helps a few people.  I've added a note in the README about the permissions issue, as well as auto-launching the tool.

Thanks for taking the time to reach out! 🙌

**Comment by Drixled** [comment]
> Sorry, i only just saw these messages now! They got lost in the many Github notifications! 😊 I'm glad this tool helps a few people. I've added a note in the README about the permissions issue, as well as auto-launching the tool.
> 
> Thanks for taking the time to reach out! 🙌

No problem my dude, everything it's fine now because of your tool. Keep the good work and have a nice day. 👊🏻
